### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by turtlepod** [easydigitaldownloads/edd-braintree#17]
I haven't test further, it's an initial testing on my local dev (braintree sandbox).
I got this error after adding data on checkout and submit.

#### Active plugins
- EDD 2.7.7
- EDD Braintree 1.1.4
- EDD Recurring 2.6.14 (I know Braintree do not support recurring payment yet)

```
Fatal error: Uncaught exception 'Braintree_Exception_Authentication' in C:\xampp\htdocs\_play\wpjob.play\wp-content\plugins\edd-braintree\braintree\lib\Braintree\Util.php:53 Stack trace: #0 C:\xampp\htdocs\_play\wpjob.play\wp-content\plugins\edd-braintree\braintree\lib\Braintree\Http.php(44): Braintree_Util::throwStatusCodeException(401) #1 C:\xampp\htdocs\_play\wpjob.play\wp-content\plugins\edd-braintree\braintree\lib\Braintree\TransactionGateway.php(388): Braintree_Http->post('/merchants/8xjg...', Array) #2 C:\xampp\htdocs\_play\wpjob.play\wp-content\plugins\edd-braintree\braintree\lib\Braintree\TransactionGateway.php(44): Braintree_TransactionGateway->_doCreate('/transactions', Array) #3 C:\xampp\htdocs\_play\wpjob.play\wp-content\plugins\edd-braintree\braintree\lib\Braintree\TransactionGateway.php(236): Braintree_TransactionGateway->create(Array) #4 C:\xampp\htdocs\_play\wpjob.play\wp-content\plugins\edd-braintree\braintree\lib\Braintree\Transaction.php(437): Braintree_TransactionGateway->sale(Array) #5 C:\xampp\htdoc in C:\xampp\htdocs\_play\wpjob.play\wp-content\plugins\edd-braintree\braintree\lib\Braintree\Util.php on line 53
```

**Comment by turtlepod** [comment]
I'm sorry, I forgot to check the "Test Mode" Payment Gateway settings.
All working fine if I tested it.
