### ISSUE TITLE
Fatal Errors on Checkout

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-braintree#2]
Some users are reporting fatal errors (white screens) upon checkout.

https://easydigitaldownloads.com/support/topic/white-screen-of-death-on-checkout-using-edd-braintree/

**Comment by cklosowski** [comment]
I set up the plugin, did the sandbox and used Test mode...getting the following:
```

Warning: require_once(Braintree/AddressGateway.php): failed to open stream: No such file or directory in /Users/cklosowski/WordPress/src/wp-content/plugins/edd-braintree/braintree/lib/Braintree.php on line 72

Fatal error: require_once(): Failed opening required 'Braintree/AddressGateway.php' (include_path='.:/Applications/MAMP/bin/php/php5.5.18/lib/php:/Users/cklosowski/WordPress/src/wp-content/plugins/edd-braintree/braintree/lib') in /Users/cklosowski/WordPress/src/wp-content/plugins/edd-braintree/braintree/lib/Braintree.php on line 72
```

**Comment by cklosowski** [comment]
After updating to the latest BrainTree libs, I get the following:
`
Fatal error: Uncaught exception 'Braintree_Exception_SSLCaFileNotFound' in /Users/cklosowski/WordPress/src/wp-content/plugins/edd-braintree/braintree/lib/Braintree/Configuration.php:211 Stack trace: #0 /Users/cklosowski/WordPress/src/wp-content/plugins/edd-braintree/braintree/lib/Braintree/Http.php(88): Braintree_Configuration->caFile() #1 /Users/cklosowski/WordPress/src/wp-content/plugins/edd-braintree/braintree/lib/Braintree/Http.php(66): Braintree_Http->_doUrlRequest('POST', 'https://api.san...', '<?xml version="...') #2 /Users/cklosowski/WordPress/src/wp-content/plugins/edd-braintree/braintree/lib/Braintree/Http.php(39): Braintree_Http->_doRequest('POST', '/merchants/vb8n...', '<?xml version="...') #3 /Users/cklosowski/WordPress/src/wp-content/plugins/edd-braintree/braintree/lib/Braintree/TransactionGateway.php(388): Braintree_Http->post('/merchants/vb8n...', Array) #4 /Users/cklosowski/WordPress/src/wp-content/plugins/edd-braintree/braintree/lib/Braintree/TransactionGateway.php(44): Braintree_TransactionGateway->_doC in /Users/cklosowski/WordPress/src/wp-content/plugins/edd-braintree/braintree/lib/Braintree/Configuration.php on line 211`

**Comment by cklosowski** [comment]
@pippinsplugins can you try this out locally and see if you are good in test mode
